### PR TITLE
Change arguments for actingAs in the nova test module

### PR DESCRIPTION
**Pull request by wolfrednicolas**

### CODE REVIEW

**Comment by wolfrednicolas** [comment]
@drewroberts there are two things here

1 - there was a bug in one of the methods called `scopeVisibleBy` of the `Theme` model, when you call the package `escape-room` you got 

PHP Fatal error:  Declaration of Tipoff\EscapeRoom\Models\Theme::scopeVisibleBy($query, $user) must be compatible with Tipoff\Support\Models\BaseModel::scopeVisibleBy(Illuminate\Database\Eloquent\Builder $query, Tipoff\Support\Contracts\Models\UserInterface $user): Illuminate\Database\Eloquent\Builder in /home/vagrant/code/packages-escape/escape-room/src/Models/Theme.php on line 154

**this was solved**

However; if I run the test get `green` in the prefer-stable but in the `prefer-lowest ` get `red`... (the error is related to the user)

Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: users.email (SQL: insert into "users" ("updated_at", "created_at") values (2021-03-05 17:39:02, 2021-03-05 17:39:02))


@pdbreen any thought?

**Comment by pdbreen** [comment]
@wolfrednicolas replace any use of `Tipoff\TestSupport\Models\User` with `Tipoff\Authorization\Models\User` within the `tests\...` directory tree.

**Comment by pdbreen** [comment]
@wolfrednicolas  Oops -- just re-read your comment - missed that it was prefer lowest only error.  Update min version number for tipoff/test-support to 1.1.2

**Comment by wolfrednicolas** [comment]
@pdbreen now it has the error with different class **(only prefer-lowest version)**

1) Tipoff\EscapeRoom\Tests\Feature\Nova\EscapeRoomLocationResourceTest::index
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: locations.gmb_account_id (SQL: insert into "locations" ("name", "slug", "title_part", "timezone", "market_id", "creator_id", "updater_id", "contact_email", "abbreviation", "updated_at", "created_at") values (Prosaccoshire, prosaccoshire, Prosaccoshire, Pacific/Fiji, 1, 1, 1, prosaccoshire@thegreatescaperoom.com, PRO...X, 2021-03-05 18:38:45, 2021-03-05 18:38:45))

**Comment by pdbreen** [comment]
@wolfrednicolas - ok, for this one, you need to bump min version of tipoff/locations - looks like  2.3.2 is current

**Comment by wolfrednicolas** [comment]
Thank you for helping me @pdbreen 

@drewroberts this PR is ready to merge and then you should release a new version for `escape-room` and the call it in other packages that has it as dependecy

**Review by drewroberts — APPROVED** [review]
THANK YOU! 🔱

**Pull request merged**
